"""step 5: per-tenant cpv/keywords/portals config

Revision ID: 92041be0f186
Revises: b6d81352be4c
Create Date: 2026-07-04 21:13:51.523207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92041be0f186'
down_revision: Union[str, Sequence[str], None] = 'b6d81352be4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_cpv',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'code')
    )
    op.create_table('tenant_keywords',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('terms', sa.Text(), server_default='{}', nullable=False),
    sa.Column('distinctive', sa.Text(), server_default='[]', nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('tenant_portals',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), server_default='api', nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_portals')
    op.drop_table('tenant_keywords')
    op.drop_table('tenant_cpv')
    # ### end Alembic commands ###
