"""initial schema

Revision ID: b6d81352be4c
Revises: 
Create Date: 2026-07-04 20:39:03.450976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d81352be4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id')
    )
    op.create_table('translations',
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('cached_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('content_hash')
    )
    op.create_table('pipeline',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('pub_number', sa.String(), nullable=False),
    sa.Column('submission_status', sa.Text(), server_default='not_started', nullable=False),
    sa.Column('deadline_override', sa.Text(), nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_date', sa.Text(), nullable=True),
    sa.Column('result_due', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), server_default='pending', nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'pub_number')
    )
    op.create_table('tenders',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('source', sa.Text(), server_default='', nullable=False),
    sa.Column('pub_number', sa.Text(), server_default='', nullable=False),
    sa.Column('tag_line', sa.Text(), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('buyer', sa.Text(), server_default='', nullable=False),
    sa.Column('country', sa.Text(), server_default='', nullable=False),
    sa.Column('place', sa.Text(), server_default='', nullable=False),
    sa.Column('category', sa.Text(), server_default='', nullable=False),
    sa.Column('procedure', sa.Text(), server_default='', nullable=False),
    sa.Column('pub_date', sa.Text(), server_default='', nullable=False),
    sa.Column('deadline', sa.Text(), server_default='', nullable=False),
    sa.Column('cpv_codes', sa.Text(), server_default='[]', nullable=False),
    sa.Column('matched_terms', sa.Text(), server_default='[]', nullable=False),
    sa.Column('match_source', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), server_default='', nullable=False),
    sa.Column('first_seen', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='new', nullable=False),
    sa.Column('exclude_reason', sa.Text(), server_default='', nullable=False),
    sa.Column('value', sa.Text(), server_default='', nullable=False),
    sa.Column('value_currency', sa.Text(), server_default='', nullable=False),
    sa.Column('value_eur', sa.Text(), server_default='', nullable=False),
    sa.Column('fx_rate_date', sa.Text(), server_default='', nullable=False),
    sa.Column('supersedes', sa.Text(), server_default='[]', nullable=False),
    sa.Column('language', sa.Text(), server_default='', nullable=False),
    sa.Column('tag_line_en', sa.Text(), server_default='', nullable=False),
    sa.Column('description_en', sa.Text(), server_default='', nullable=False),
    sa.Column('translation_status', sa.Text(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenders')
    op.drop_table('pipeline')
    op.drop_table('translations')
    op.drop_table('tenants')
    # ### end Alembic commands ###
